function [controls, frame_num, z_num, particle_num, ...
    add_spot, smart_add_spot, delete_spot] = setupControls(Overlay)
%SETUPCONTROLS Summary of this function goes here
%   Detailed explanation goes here
controls = uipanel(Overlay, 'Title', 'Controls', 'Position', ...
    [0.85, .06, 0.15, 0.9], 'units', 'normalized', 'FontSize', 12);
uicontrol('Style', 'text', 'Parent', controls, 'Units', ...
    'normalized', 'String', 'Frame: ', 'Position', [0.05, .9, 0.35, 0.08], ...
    'FontSize', 10);
frame_num = uicontrol('Style', 'edit', 'Parent', controls, 'Units', ...
    'normalized', 'String', '1', 'Position', [.4, .9, .55, 0.08], ...
    'FontSize', 12);


uicontrol('Style', 'text', 'Parent', controls, 'Units', ...
    'normalized', 'String', 'Z-Slice: ', 'Position', [0.05, .8, 0.35, 0.08], ...
    'FontSize', 10);
z_num = uicontrol('Style', 'edit', 'Parent', controls, 'Units', ...
    'normalized', 'String', '6', 'Position', [.4, .8, .55, 0.08], ...
    'FontSize', 12);
uicontrol('Style', 'text', 'Parent', controls, 'Units', ...
    'normalized', 'String', 'Particle: ', 'Position', [0.05, .7, 0.35, 0.08], ...
    'FontSize', 10);
particle_num = uicontrol('Style', 'edit', 'Parent', controls, 'Units', ...
    'normalized', 'String', '1', 'Position', [.4, .7, .55, 0.08], ...
    'FontSize', 12);
add_spot = uicontrol('Style', 'pushbutton','Parent', controls, 'Units', 'normalized',...
    'Position', [0.05, 0.5, 0.4, 0.08], 'String', 'Add Spot', 'FontSize', 10);
smart_add_spot = uicontrol('Style', 'checkbox', 'Parent', controls, ...
    'Units', 'normalized', 'Position', [0.55, 0.5, 0.4, 0.08], 'String', ...
    'Smart add', 'FontSize', 10);
delete_spot = uicontrol('Style', 'pushbutton','Parent', controls, 'Units', 'normalized',...
    'Position', [0.05, 0.3, 0.4, 0.08], 'String', 'Delete Spot', 'FontSize', 10);
end

