function [controls_fig, frame_num, z_num, particle_num, ...
    add_spot, smart_add_spot, delete_spot] = setupControls(Overlay)
%SETUPCONTROLS Summary of this function goes here
%   Detailed explanation goes here
Overlay.Units = 'pixels';
loc = [Overlay.Position(1) + Overlay.Position(3) + 10, Overlay.Position(2)];
screen_size = get(0, 'screensize');
dim = [screen_size(3) - loc(1) - 10, Overlay.Position(4)];
controls_fig = uifigure('Position', [loc(1), loc(2), dim(1), dim(2)]);
controls = uipanel(controls_fig, 'Title', 'Controls', 'Position', ...
    [0, 0, dim(1), dim(2)], ...
    'FontSize', 12, 'Scrollable', 'on');
Overlay.Units = 'normalized';
offset = 0.5 * dim(2);
uilabel('Parent', controls, 'Text', 'Frame: ', 'Position', ...
    [0.05 * dim(1), .9 * dim(2) + offset, 0.35 * dim(1), 0.08 * dim(2)], ...
    'FontSize', 10);
frame_num = uieditfield('Parent', controls, 'Value', '1', 'Position', ...
    [.4 * dim(1), .9 * dim(2) + offset, .4 * dim(1), 0.08 * dim(2)], 'FontSize', 12);

uilabel('Parent', controls,'Text', 'Z-Slice: ', 'Position', ...
    [0.05 * dim(1), .8 * dim(2) + offset, 0.35 * dim(1), 0.08 * dim(2)], 'FontSize', 10);
z_num = uieditfield('Parent', controls, 'Value', '6', 'Position', ...
    [.4 * dim(1), .8 * dim(2) + offset, .4 * dim(1), 0.08 * dim(2)], ...
    'FontSize', 12);
uilabel('Parent', controls, 'Text', 'Particle: ', 'Position', ...
    [0.05 * dim(1), .7 * dim(2) + offset, 0.35 * dim(1), 0.08 * dim(2)], ...
    'FontSize', 10);
particle_num = uieditfield('Parent', controls, 'Value', '1', ...
    'Position', [.4 * dim(1), .7 * dim(2) + offset, .4 * dim(1), 0.08 * dim(2)], ...
    'FontSize', 12);
add_spot = uibutton('Parent', controls,...
    'Position', [0.05 * dim(1), 0.5 * dim(2) + offset, 0.35 * dim(1), 0.08 * dim(2)]...
    , 'Text', 'Add Spot', 'FontSize', 10);
smart_add_spot = uicheckbox('Parent', controls, ...
    'Position', [0.45 * dim(1), 0.5 * dim(2) + offset, 0.4 * dim(1), 0.08 * dim(2)], 'Text', ...
    'Smart add', 'FontSize', 10);
delete_spot = uibutton('Parent', controls,...
    'Position', [0.05 * dim(1), 0.3 * dim(2) + offset, 0.4 * dim(1), 0.08 * dim(2)], ...
    'Text', 'Delete Spot', 'FontSize', 10);
end

