function processLIFFrame(numberOfFrames, Prefix, OutputFolder, LIFImages, framesIndex,...
  seriesIndex, NChannels, NSlices, ExperimentType, Channel1, Channel2, Channel3, ProjectionType,...
  fiducialChannel, histoneChannel, ReferenceHist, coatChannel, inputProteinChannel, zslicesPadding, lowbit)
  
for channelIndex = 1:NChannels
    processLIFChannel(ExperimentType, channelIndex, numberOfFrames, Prefix, OutputFolder,...
      LIFImages, framesIndex, seriesIndex, NChannels, NSlices,...
      coatChannel, inputProteinChannel, zslicesPadding, lowbit);
end
  
  %Now copy nuclear tracking images
  if fiducialChannel
    generateNuclearChannel(numberOfFrames, LIFImages,...
        framesIndex, seriesIndex, NSlices, NChannels, fiducialChannel, ProjectionType,...
        ExperimentType, Channel1, Channel2,...
        Channel3, ReferenceHist, OutputFolder, Prefix, lowbit);
  end
  
end
