function processMovieFrame(numberOfFrames, Prefix, OutputFolder, movieImages, framesIndex,...
  seriesIndex, NChannels, NSlices, ExperimentType, Channel1, Channel2, Channel3, ProjectionType,...
  fiducialChannel, histoneChannel, ReferenceHist, coatChannel, inputProteinChannel, zslicesPadding, lowbit)
  
for channelIndex = 1:NChannels
    processMovieChannel(ExperimentType, channelIndex, numberOfFrames, Prefix, OutputFolder,...
      movieImages, framesIndex, seriesIndex, NChannels, NSlices,...
      coatChannel, inputProteinChannel, zslicesPadding, lowbit);
end
  
  %Now copy nuclear tracking images
  if fiducialChannel
    generateNuclearChannel(numberOfFrames, movieImages,...
        framesIndex, seriesIndex, NSlices, NChannels, fiducialChannel, ProjectionType,...
        ExperimentType, Channel1, Channel2,...
        Channel3, ReferenceHist, OutputFolder, Prefix, lowbit);
  end
  
end
