function filteredClusters = filterClustersForClusterAnalysis(...
                                        Clusters, schnitzcells, varargin)
% DESCRIPTION
% This function filters MS2 Particles structure based on user-input quality
% control metrics.
%
%
% ARGUMENTS
% Clusters: Clusters structure (generated by sortSpotsByNuclei function)
%
% schnitzcells: 
%
%
% OPTIONS
% onlyFullyApproved: NOT implemented yet, but would exclude yellow-flagged
%                    nuclei (e.g. nuclei that have drifted)
%
% OUTPUT
% filteredClusters: Clusters structure with all nuclei that don't meet
%                   QC criteria removed
%
% Author (contact): Meghan Turner (meghan_turner@berkeley.edu)
% Created: 2022/05/24
% Last Updated:

%% QC filters on schnitzcells

% Keep only nuclei whose full lineage is approved (defined as green- or
% yellow-flagged)
% 1 or 2 is approved, 0 is not approved
approvedSchnitz = ([schnitzcells.Approved] ~= 0);

schnitzIDsToKeep = find(approvedSchnitz);

%% Translate that over to filtering the Cluster structure
[~, approvedNucleiIndices,~] = intersect([Clusters.Nucleus], schnitzIDsToKeep);
ClusterNucleiToKeep = Clusters(approvedNucleiIndices);

%% Check that we found at least one particle that meets QC criteria
filteredClusters = ClusterNucleiToKeep;

if isempty(filteredClusters)
    error('No particles met your filtering criteria. Please adjust inputs and try again.')
end