% No histone path of traackmRNADynamics is processed separately
trackmRNADynamicsNotHistoneTestCase = testTrackmRNADynamicsNotHistone_2015_07_25_P2P_75uW_bi_short;
generateExpectedDataTrackmRNADynamicsNotHistone(trackmRNADynamicsNotHistoneTestCase);
exit;
