function Particles = initializeParticles()

    Particles = struct(...
        'Frame',{}, ...
        'Index', {}, ...
        'xPos', {}, ...
        'yPos', {}, ...
        'zPosDetrended', {}, ...
        'zPos', {}, ...
        'Nucleus', {}, ...
        'firstFrame', {}, ...
        'lastFrame', {}, ...
        'framesFull', {}, ...
        'logL', {}, ...
        'xPosInf', {}, ...
        'yPosInf', {}, ...
        'zPosDetrendedInf', {}, ...
        'xPosSEInf', {}, ...
        'yPosSEInf', {}, ...
        'zPosSEInf', {}, ...
        'zPosInf', {}, ...
        'smoothedPredictions', {},...
        'smoothedPredictionsSE',{});